accounts/urls.py
from django.urls import path
from .views import ProfileListView, SignUpView, ProfileDetail

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile_list/', ProfileListView.as_view(), name='profile_list'),
    path('profile/<int:pk>/', ProfileDetail.as_view(), name='profile_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('jobs.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

jobs/urls.py
from django.urls import path
from .views import JobListView, JobDetailView, ApplyView, JobCreateView, SearchResultsListView

urlpatterns = [
    path('', JobListView.as_view(), name='job_list'),
    path('new/', JobCreateView.as_view(), name='new_job'),
    path('job/<int:pk>/', JobDetailView.as_view(), name='job_detail'),
    path('job/<int:pk>/apply', ApplyView.as_view(), name='job_apply'),
    path('search/', SearchResultsListView.as_view(),
         name='search_results'),

]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from taggit.managers import TaggableManager
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.contrib.auth import get_user_model
from django.dispatch import receiver
from django.db.models.signals import post_save


TAGS = TaggableManager(
    verbose_name="programming languages", help_text="A comma-separated list of Programming Languages.")
HITS = GenericRelation(HitCount, object_id_field='object_pk',
                       related_query_name='hit_count_generic_relation')


class CustomUser(AbstractUser):

    LEVELS = (
        ('JR', 'Junior'),
        ('MID', 'Mid-Level'),
        ('SR', 'Senior'),

    )
    national_id = models.PositiveIntegerField(null=True)
    city = models.CharField(max_length=50, null=True)
    bio = models.TextField(null=True)
    experience_level = models.CharField(
        choices=LEVELS, max_length=3, default='JR',)
    programming_languages = TAGS


class Profile(models.Model):
    employee = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE, related_name='profile'
    )

    number_of_views = HITS

    # Create a profile when a new user is created

    @receiver(post_save, sender=get_user_model())
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(employee=instance)

    @receiver(post_save, sender=get_user_model())
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return self.employee.username

jobs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django_boost.models.fields import AutoOneToOneField


class Job(models.Model):
    LEVELS = (
        ("JR", "Junior"),
        ("MID", "Mid-Level"),
        ("SR", "Senior"),
    )
    title = models.CharField(max_length=50)
    published_at = models.DateTimeField(auto_now=True)
    location = models.CharField(max_length=50)
    experience_level = models.CharField(
        choices=LEVELS,
        max_length=3,
        default="JR",
    )
    description = models.TextField()
    employee = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="job"
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("job_list")


class Application(models.Model):
    brief = models.TextField(max_length=500)
    job = models.ForeignKey(
        Job,
        on_delete=models.CASCADE,
        related_name="applications",
    )
    employee = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="applications",
    )

    def __str__(self):
        return self.job.title

    def get_absolute_url(self):
        return reverse("job_detail", args=[str(self.job.id)])


class EmploymentProcess(models.Model):
    STATUS = (
        ("APPLIED", "Applied"),
        ("APROVED", "Aproved"),
        ("REJECTED", "Rejected"),
    )
    application = AutoOneToOneField(
        Application,
        primary_key=True,
        related_name="employment_process",
        on_delete=models.CASCADE,
    )
    status = models.CharField(choices=STATUS, default="APPLIED", max_length=10)

    def __str__(self):
        return self.status

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email', 'national_id', 'city', 'bio',
                  'experience_level', 'programming_languages')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'national_id', 'city', 'bio',
                  'experience_level', 'programming_languages')

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from hitcount.views import HitCountDetailView
from accounts.models import Profile
from .forms import CustomUserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'accounts/profile_list.html'
    context_object_name = 'profile_list'


class ProfileDetail(LoginRequiredMixin, HitCountDetailView):
    model = Profile
    template_name = 'accounts/profile_detail.html'
    count_hit = True

jobs/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Job, Application
from django.db.models import Q


class JobListView(ListView):
    model = Job
    template_name = "jobs/home.html"
    context_object_name = "job_list"
    paginate_by = 5

    # sort jobs by newest
    def get_queryset(self, *args, **kwargs):
        qs = super(JobListView, self).get_queryset(*args, **kwargs)
        qs = qs.order_by("-published_at")
        return qs


class JobDetailView(LoginRequiredMixin, DetailView):
    model = Job
    template_name = "jobs/job_detail.html"


class JobCreateView(LoginRequiredMixin, CreateView):
    model = Job
    template_name = "jobs/new_job.html"
    fields = ["title", "location", "experience_level", "description"]

    def form_valid(self, form):
        form.instance.employee = self.request.user
        return super().form_valid(form)


class ApplyView(LoginRequiredMixin, CreateView):
    model = Application
    template_name = "jobs/job_apply.html"
    fields = [
        "brief",
    ]

    # Prefill user and job when apply to a job
    def form_valid(self, form,):
        form.instance.employee = self.request.user
        pk = self.kwargs.get(self.pk_url_kwarg)
        job = Job.objects.get(pk=pk)
        form.instance.job = job

        return super().form_valid(form)


class SearchResultsListView(ListView):
    model = Job
    context_object_name = 'job_search_list'
    template_name = 'jobs/search_results.html'
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Job.objects.filter(
            Q(title__icontains=query) | Q(location__icontains=query) | Q(
                experience_level__icontains=query) | Q(description__icontains=query)

        )

templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Hi {{user.username}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                               
                                <div class="jobs_conetent">
                                    <a href="{% url 'profile' %}"><h4>{{user.username}} Profile</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{user.city}}</p>
                                        </div>
                                       
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                   </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            {% comment %} <h4>Number of Profile Views : <p>{{% get_hit_count for user.profile %}}</p></h4> {% endcomment %}
                           
                          
                        </div>
                        <div class="single_wrap">
                            <h4>Bio</h4>
                            <p>{{user.bio}}</p>
                          
                        </div>
                        <div class="single_wrap">
                            <h4>experience_level</h4>
                            <p>{{user.experience_level}}</p>
                          
                        </div>
                        <div class="single_wrap">
                            <h4>programming_languages</h4>
                                {% for tag in user.programming_languages.all %}
                                    <p> {{ tag.name }}</p>
                                {% endfor %}
                            
                            
                            
                        </div>
                  
                    
                    </div>

                
            
                 

                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                      
                       
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/accounts/profile_detail.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Hi {{user.username}} <br> </h3>
                            {% if  not user.username == profile.employee.username %}
                           <h4> this is {{profile.employee.username}} Profile </h4>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                               
                                <div class="jobs_conetent">
                                    <a href="{% url 'profile_detail' profile.pk     %}"><h4>{{profile.employee.username}} Profile</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{profile.employee.city}}</p>
                                        </div>
                                       
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                   </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Number of Profile Views : <p>{% get_hit_count for profile %}</p></h4>
                           
                          
                        </div>
                        <div class="single_wrap">
                            <h4>Bio</h4>
                            <p>{{profile.employee.user.bio}}</p>
                          
                        </div>
                        <div class="single_wrap">
                            <h4>experience_level</h4>
                            <p>{{profile.employee.experience_level}}</p>
                          
                        </div>
                        <div class="single_wrap">
                            <h4>programming_languages</h4>
                                {% for tag in profile.employee.programming_languages.all %}
                                    <p> {{ tag.name }}</p>
                                {% endfor %}
                            
                            
                            
                        </div>
                  
                    
                    </div>

                
            
                 

                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                      
                       
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/accounts/profile_list.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Profiles List</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="col-md-6">
{% for profile in profile_list %}
<h4>Profile : <a href="{% url 'profile_detail' profile.pk %}">
    {{profile.employee.username}}   </h4>
 </a>
 <h5>Number of Profile Views: {% get_hit_count for profile %}</h5>
 <br>
{% endfor%}

</div>
<br>
<br>

{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'job_list' %}">
                                                home</a></li>
                                                <li><a href="{% url 'profile_list' %}">
                                                    Profiles list</a></li>
                                            
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                 
                                    {% if user.is_authenticated %}
                                    <div class="phone_num d-none d-xl-block">
                                        
                                        <a href="{% url 'profile_detail' user.profile.pk  %}">Hi {{ user.username }}</a>
                                    </div>
                                    <div class="phone_num d-none d-xl-block">
                                        
                                        <a href="{% url 'logout' %}">Log out</a>
                                    </div>
                                    {% else %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'login' %}">Log in</a>
                                    </div>
                                    {% endif%}
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'new_job' %}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

 
{% block content %}

{% endblock content %}

 

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                  
                   
                    
                   
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js'"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'"></script>
    <script src="{% static 'js/popper.min.js'"></script>
    <script src="{% static 'js/bootstrap.min.js'"></script>
    <script src="{% static 'js/owl.carousel.min.js'"></script>
    <script src="{% static 'js/isotope.pkgd.min.js'"></script>
    <script src="{% static 'js/ajax-form.js'"></script>
    <script src="{% static 'js/waypoints.min.js'"></script>
    <script src="{% static 'js/jquery.counterup.min.js'"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js'"></script>
    <script src="{% static 'js/scrollIt.js'"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js'"></script>
    <script src="{% static 'js/wow.min.js'"></script>
    <script src="{% static 'js/nice-select.min.js'"></script>
    <script src="{% static 'js/jquery.slicknav.min.js'"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'"></script>
    <script src="{% static 'js/plugins.js'"></script>
    <!-- <script 'src="js/gijgo.min.js"></script> -->
    <script src="{% static 'js/range.js'"></script>

    <!--contact j's-->
    <script src="{% static 'js/contact.js'"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js'"></script>
    <script src="{% static 'js/jquery.form.js'"></script>
    <script src="{% static 'js/jquery.validate.min.js'"></script>
    <script src="{% static 'js/mail-script.js'"></script>

    <script src="{% static 'js/main.js'"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
</body>

</html>

templates/jobs/job_apply.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Apply for the job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="col-md-6">
<h5>  Tell us a summery about you and why should we hire you.</h5>

<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
<input type="submit" value="Apply">
</form>
</div>
<br>
<br>

{% endblock content %}

templates/jobs/job_detail.html
{% extends 'base.html' %}

{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                               
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{job.location}}</p>
                                        </div>
                                       
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                   </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                          
                        </div>
                    
                  
                    
                    </div>
                       
                    <div class="apply_job_form white-bg">
 
                                   
                                        
                            
                                            
                                       
                                        
                                            <form action="#">
                                                <div class="row">
                                                
                                                    <div class="col-md-12">
                                                        <div class="submit_btn">
                                                            
                                                            <a href="{% url 'job_apply' job.pk %}" class="boxed-btn3">
                                                                Apply 
                                                            </a>
                                                        
                                                        
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                           
                                            
                                            
                                        
                                        
                        
                       
                    </div>
            
                 

                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published_at|date:"F d Y"}}</span></li>
                                
                               
                                <li>Location: <span>{{job.location}}</span></li>
                                <li>Job Level: <span>{{job.get_experience_level_display}}</span></li>
                            </ul>
                        </div>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/jobs/new_job.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Post a new Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="col-md-6">



<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
<input type="submit" value="Post">
</form>
<br>
<br>

</div>


{% endblock content %}